name: Validate and Deploy CloudGuard Policies

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/
          opa test opa/policies/ -v

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init & Validate
        run: |
          cd terraform/environments/dev
          terraform init -backend=false
          terraform validate
