name: Test and Deploy CloudGuard AWS Policies

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------
      # Checkout code
      # ---------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------
      # Set up OPA using official action
      # ---------------------------
      - name: Set up OPA
        uses: open-policy-agent/setup-opa@v1

      - name: Verify OPA installation
        run: opa version

      # ---------------------------
      # Run OPA policy tests
      # ---------------------------
      - name: Test OPA Policies
        run: |
          echo "Running OPA policy tests..."
          opa test opa/policies/ -v

      # ---------------------------
      # Setup Terraform
      # ---------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # ---------------------------
      # Terraform Init and Apply
      # ---------------------------
      - name: Deploy AWS Infrastructure
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      # ---------------------------
      # Optional: Output Lambda Info
      # ---------------------------
      - name: Output Lambda Info
        run: |
          cd terraform
          terraform output
